import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

// 以 package.json 为版本源，同步到 plugin.json
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
const version = pkg.version;

const pluginPath = join(root, 'plugin.json');
const manifest = JSON.parse(readFileSync(pluginPath, 'utf-8'));
if (manifest.version !== version) {
  manifest.version = version;
  writeFileSync(pluginPath, JSON.stringify(manifest, null, 2) + '\n', 'utf-8');
  console.log(`  ℹ️  synced plugin.json version → ${version}`);
}

const lockPath = join(root, 'package-lock.json');
const lock = JSON.parse(readFileSync(lockPath, 'utf-8'));
if (lock.version !== version) {
  lock.version = version;
  writeFileSync(lockPath, JSON.stringify(lock, null, 2) + '\n', 'utf-8');
  console.log(`  ℹ️  synced package-lock.json version → ${version}`);
}

const outDir = join(root, 'src', 'generated');
mkdirSync(outDir, { recursive: true });

const code = `// Auto-generated by scripts/prebuild.mjs — do not edit manually
export const PLUGIN_VERSION = '${version}';
`;

writeFileSync(join(outDir, 'version.ts'), code, 'utf-8');
console.log(`  ℹ️  generated src/generated/version.ts (version=${version})`);
